// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID           string `json:"id"`
	ScoreboardID string `json:"scoreboardID"`
	Text         string `json:"text"`
	User         string `json:"user"`
	CreatedAt    string `json:"createdAt"`
}

type NewComment struct {
	ID           *string `json:"id,omitempty"`
	ScoreboardID string  `json:"scoreboardID"`
	Text         string  `json:"text"`
	User         string  `json:"user"`
}

type NewScoreboard struct {
	ID        *string   `json:"id,omitempty"`
	StartedAt string    `json:"startedAt"`
	Players   []*string `json:"players,omitempty"`
	Winner    string    `json:"winner"`
}

type Scoreboard struct {
	ID        string     `json:"id"`
	StartedAt string     `json:"startedAt"`
	Players   []*string  `json:"players,omitempty"`
	Related   []*Comment `json:"related"`
	Winner    string     `json:"winner"`
}
