// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: proto/mafia-game.proto

package mafia_game

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Roles int32

const (
	Roles_Mafia        Roles = 0
	Roles_Commissioner Roles = 1
	Roles_Civilian     Roles = 2
	Roles_Undefined    Roles = 3
)

// Enum value maps for Roles.
var (
	Roles_name = map[int32]string{
		0: "Mafia",
		1: "Commissioner",
		2: "Civilian",
		3: "Undefined",
	}
	Roles_value = map[string]int32{
		"Mafia":        0,
		"Commissioner": 1,
		"Civilian":     2,
		"Undefined":    3,
	}
)

func (x Roles) Enum() *Roles {
	p := new(Roles)
	*p = x
	return p
}

func (x Roles) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Roles) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mafia_game_proto_enumTypes[0].Descriptor()
}

func (Roles) Type() protoreflect.EnumType {
	return &file_proto_mafia_game_proto_enumTypes[0]
}

func (x Roles) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Roles.Descriptor instead.
func (Roles) EnumDescriptor() ([]byte, []int) {
	return file_proto_mafia_game_proto_rawDescGZIP(), []int{0}
}

type State int32

const (
	State_connected State = 0
	State_left      State = 1
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "connected",
		1: "left",
	}
	State_value = map[string]int32{
		"connected": 0,
		"left":      1,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mafia_game_proto_enumTypes[1].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_proto_mafia_game_proto_enumTypes[1]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_proto_mafia_game_proto_rawDescGZIP(), []int{1}
}

type SessionReadiness struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionReady bool     `protobuf:"varint,1,opt,name=session_ready,json=sessionReady,proto3" json:"session_ready,omitempty"`
	Role         Roles    `protobuf:"varint,2,opt,name=role,proto3,enum=Roles" json:"role,omitempty"`
	Players      []string `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *SessionReadiness) Reset() {
	*x = SessionReadiness{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mafia_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionReadiness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReadiness) ProtoMessage() {}

func (x *SessionReadiness) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mafia_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReadiness.ProtoReflect.Descriptor instead.
func (*SessionReadiness) Descriptor() ([]byte, []int) {
	return file_proto_mafia_game_proto_rawDescGZIP(), []int{0}
}

func (x *SessionReadiness) GetSessionReady() bool {
	if x != nil {
		return x.SessionReady
	}
	return false
}

func (x *SessionReadiness) GetRole() Roles {
	if x != nil {
		return x.Role
	}
	return Roles_Mafia
}

func (x *SessionReadiness) GetPlayers() []string {
	if x != nil {
		return x.Players
	}
	return nil
}

type ConnectToSessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success   bool              `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Readiness *SessionReadiness `protobuf:"bytes,2,opt,name=readiness,proto3" json:"readiness,omitempty"`
}

func (x *ConnectToSessionResponse) Reset() {
	*x = ConnectToSessionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mafia_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectToSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectToSessionResponse) ProtoMessage() {}

func (x *ConnectToSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mafia_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectToSessionResponse.ProtoReflect.Descriptor instead.
func (*ConnectToSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_mafia_game_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectToSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectToSessionResponse) GetReadiness() *SessionReadiness {
	if x != nil {
		return x.Readiness
	}
	return nil
}

type LeaveSessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *LeaveSessionResponse) Reset() {
	*x = LeaveSessionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mafia_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveSessionResponse) ProtoMessage() {}

func (x *LeaveSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mafia_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveSessionResponse.ProtoReflect.Descriptor instead.
func (*LeaveSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_mafia_game_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListConnectionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login     string               `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	State     State                `protobuf:"varint,2,opt,name=state,proto3,enum=State" json:"state,omitempty"`
	Time      *timestamp.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Readiness *SessionReadiness    `protobuf:"bytes,4,opt,name=readiness,proto3" json:"readiness,omitempty"`
}

func (x *ListConnectionsResponse) Reset() {
	*x = ListConnectionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mafia_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectionsResponse) ProtoMessage() {}

func (x *ListConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mafia_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectionsResponse.ProtoReflect.Descriptor instead.
func (*ListConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_mafia_game_proto_rawDescGZIP(), []int{3}
}

func (x *ListConnectionsResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *ListConnectionsResponse) GetState() State {
	if x != nil {
		return x.State
	}
	return State_connected
}

func (x *ListConnectionsResponse) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ListConnectionsResponse) GetReadiness() *SessionReadiness {
	if x != nil {
		return x.Readiness
	}
	return nil
}

type VoteForMafiaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MafiaGuess string `protobuf:"bytes,1,opt,name=mafia_guess,json=mafiaGuess,proto3" json:"mafia_guess,omitempty"`
	Login      string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
}

func (x *VoteForMafiaRequest) Reset() {
	*x = VoteForMafiaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mafia_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteForMafiaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteForMafiaRequest) ProtoMessage() {}

func (x *VoteForMafiaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mafia_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteForMafiaRequest.ProtoReflect.Descriptor instead.
func (*VoteForMafiaRequest) Descriptor() ([]byte, []int) {
	return file_proto_mafia_game_proto_rawDescGZIP(), []int{4}
}

func (x *VoteForMafiaRequest) GetMafiaGuess() string {
	if x != nil {
		return x.MafiaGuess
	}
	return ""
}

func (x *VoteForMafiaRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type VoteForMafiaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KilledUser     string `protobuf:"bytes,1,opt,name=killed_user,json=killedUser,proto3" json:"killed_user,omitempty"`
	KilledUserRole Roles  `protobuf:"varint,2,opt,name=killed_user_role,json=killedUserRole,proto3,enum=Roles" json:"killed_user_role,omitempty"`
}

func (x *VoteForMafiaResponse) Reset() {
	*x = VoteForMafiaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mafia_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteForMafiaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteForMafiaResponse) ProtoMessage() {}

func (x *VoteForMafiaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mafia_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteForMafiaResponse.ProtoReflect.Descriptor instead.
func (*VoteForMafiaResponse) Descriptor() ([]byte, []int) {
	return file_proto_mafia_game_proto_rawDescGZIP(), []int{5}
}

func (x *VoteForMafiaResponse) GetKilledUser() string {
	if x != nil {
		return x.KilledUser
	}
	return ""
}

func (x *VoteForMafiaResponse) GetKilledUserRole() Roles {
	if x != nil {
		return x.KilledUserRole
	}
	return Roles_Mafia
}

type MoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Login  string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mafia_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mafia_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_mafia_game_proto_rawDescGZIP(), []int{6}
}

func (x *MoveRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *MoveRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type MoveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Accepted bool   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason   string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mafia_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mafia_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_proto_mafia_game_proto_rawDescGZIP(), []int{7}
}

func (x *MoveResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *MoveResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GameStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Active bool  `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	Winner Roles `protobuf:"varint,2,opt,name=winner,proto3,enum=Roles" json:"winner,omitempty"`
}

func (x *GameStatus) Reset() {
	*x = GameStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mafia_game_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStatus) ProtoMessage() {}

func (x *GameStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mafia_game_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStatus.ProtoReflect.Descriptor instead.
func (*GameStatus) Descriptor() ([]byte, []int) {
	return file_proto_mafia_game_proto_rawDescGZIP(), []int{8}
}

func (x *GameStatus) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *GameStatus) GetWinner() Roles {
	if x != nil {
		return x.Winner
	}
	return Roles_Mafia
}

type DayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Victim string   `protobuf:"bytes,1,opt,name=victim,proto3" json:"victim,omitempty"`
	Alive  []string `protobuf:"bytes,2,rep,name=alive,proto3" json:"alive,omitempty"`
}

func (x *DayResponse) Reset() {
	*x = DayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mafia_game_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayResponse) ProtoMessage() {}

func (x *DayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mafia_game_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayResponse.ProtoReflect.Descriptor instead.
func (*DayResponse) Descriptor() ([]byte, []int) {
	return file_proto_mafia_game_proto_rawDescGZIP(), []int{9}
}

func (x *DayResponse) GetVictim() string {
	if x != nil {
		return x.Victim
	}
	return ""
}

func (x *DayResponse) GetAlive() []string {
	if x != nil {
		return x.Alive
	}
	return nil
}

type StatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alive      []string    `protobuf:"bytes,1,rep,name=alive,proto3" json:"alive,omitempty"`
	GameStatus *GameStatus `protobuf:"bytes,2,opt,name=game_status,json=gameStatus,proto3" json:"game_status,omitempty"`
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mafia_game_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mafia_game_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_mafia_game_proto_rawDescGZIP(), []int{10}
}

func (x *StatusResponse) GetAlive() []string {
	if x != nil {
		return x.Alive
	}
	return nil
}

func (x *StatusResponse) GetGameStatus() *GameStatus {
	if x != nil {
		return x.GameStatus
	}
	return nil
}

type ExitGameSessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExitGameSessionResponse) Reset() {
	*x = ExitGameSessionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mafia_game_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExitGameSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitGameSessionResponse) ProtoMessage() {}

func (x *ExitGameSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mafia_game_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitGameSessionResponse.ProtoReflect.Descriptor instead.
func (*ExitGameSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_mafia_game_proto_rawDescGZIP(), []int{11}
}

type DefaultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
}

func (x *DefaultRequest) Reset() {
	*x = DefaultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mafia_game_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultRequest) ProtoMessage() {}

func (x *DefaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mafia_game_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultRequest.ProtoReflect.Descriptor instead.
func (*DefaultRequest) Descriptor() ([]byte, []int) {
	return file_proto_mafia_game_proto_rawDescGZIP(), []int{12}
}

func (x *DefaultRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

var File_proto_mafia_game_proto protoreflect.FileDescriptor

var file_proto_mafia_game_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2d, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6d, 0x0a, 0x10, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x23, 0x0a,
	0x0d, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x61,
	0x64, 0x79, 0x12, 0x1a, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x06, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0x65, 0x0a, 0x18, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x54, 0x6f, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x2f,
	0x0a, 0x09, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x61, 0x64, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x52, 0x09, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x22,
	0x30, 0x0a, 0x14, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x22, 0xae, 0x01, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x06, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x12, 0x2f, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x61, 0x64, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x09, 0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x65,
	0x73, 0x73, 0x22, 0x4c, 0x0a, 0x13, 0x56, 0x6f, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x4d, 0x61, 0x66,
	0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x66,
	0x69, 0x61, 0x5f, 0x67, 0x75, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x6d, 0x61, 0x66, 0x69, 0x61, 0x47, 0x75, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x22, 0x69, 0x0a, 0x14, 0x56, 0x6f, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x4d, 0x61, 0x66, 0x69, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6b, 0x69, 0x6c, 0x6c,
	0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6b,
	0x69, 0x6c, 0x6c, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x10, 0x6b, 0x69, 0x6c,
	0x6c, 0x65, 0x64, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x06, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x0e, 0x6b, 0x69, 0x6c,
	0x6c, 0x65, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0x3b, 0x0a, 0x0b, 0x4d,
	0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x22, 0x42, 0x0a, 0x0c, 0x4d, 0x6f, 0x76, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x44, 0x0a, 0x0a,
	0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x12, 0x1e, 0x0a, 0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x06, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x06, 0x77, 0x69, 0x6e, 0x6e,
	0x65, 0x72, 0x22, 0x3b, 0x0a, 0x0b, 0x44, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x69, 0x63, 0x74, 0x69, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x76, 0x69, 0x63, 0x74, 0x69, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69,
	0x76, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x22,
	0x54, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x05, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x2c, 0x0a, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x19, 0x0a, 0x17, 0x45, 0x78, 0x69, 0x74, 0x47, 0x61, 0x6d,
	0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2a, 0x41, 0x0a, 0x05, 0x52, 0x6f, 0x6c, 0x65,
	0x73, 0x12, 0x09, 0x0a, 0x05, 0x4d, 0x61, 0x66, 0x69, 0x61, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c,
	0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x65, 0x72, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x43, 0x69, 0x76, 0x69, 0x6c, 0x69, 0x61, 0x6e, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09,
	0x55, 0x6e, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x10, 0x03, 0x2a, 0x20, 0x0a, 0x05, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x10, 0x01, 0x32, 0xd4, 0x03,
	0x0a, 0x0c, 0x4d, 0x61, 0x66, 0x69, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40,
	0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x54, 0x6f, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x0f, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x54, 0x6f, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x38, 0x0a, 0x0c, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x0f, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0f, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x0f, 0x2e,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x3d, 0x0a, 0x0c,
	0x56, 0x6f, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x4d, 0x61, 0x66, 0x69, 0x61, 0x12, 0x14, 0x2e, 0x56,
	0x6f, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x4d, 0x61, 0x66, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x4d, 0x61, 0x66, 0x69,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x08, 0x4d,
	0x61, 0x6b, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x0c, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x08, 0x53, 0x74, 0x61, 0x72, 0x74, 0x44,
	0x61, 0x79, 0x12, 0x0f, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x44, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0f, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0f, 0x45, 0x78, 0x69, 0x74, 0x47, 0x61, 0x6d, 0x65,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0f, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x45, 0x78, 0x69, 0x74, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61,
	0x66, 0x69, 0x61, 0x2d, 0x67, 0x61, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_mafia_game_proto_rawDescOnce sync.Once
	file_proto_mafia_game_proto_rawDescData = file_proto_mafia_game_proto_rawDesc
)

func file_proto_mafia_game_proto_rawDescGZIP() []byte {
	file_proto_mafia_game_proto_rawDescOnce.Do(func() {
		file_proto_mafia_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_mafia_game_proto_rawDescData)
	})
	return file_proto_mafia_game_proto_rawDescData
}

var file_proto_mafia_game_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_mafia_game_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_mafia_game_proto_goTypes = []interface{}{
	(Roles)(0),                       // 0: Roles
	(State)(0),                       // 1: State
	(*SessionReadiness)(nil),         // 2: SessionReadiness
	(*ConnectToSessionResponse)(nil), // 3: ConnectToSessionResponse
	(*LeaveSessionResponse)(nil),     // 4: LeaveSessionResponse
	(*ListConnectionsResponse)(nil),  // 5: ListConnectionsResponse
	(*VoteForMafiaRequest)(nil),      // 6: VoteForMafiaRequest
	(*VoteForMafiaResponse)(nil),     // 7: VoteForMafiaResponse
	(*MoveRequest)(nil),              // 8: MoveRequest
	(*MoveResponse)(nil),             // 9: MoveResponse
	(*GameStatus)(nil),               // 10: GameStatus
	(*DayResponse)(nil),              // 11: DayResponse
	(*StatusResponse)(nil),           // 12: StatusResponse
	(*ExitGameSessionResponse)(nil),  // 13: ExitGameSessionResponse
	(*DefaultRequest)(nil),           // 14: DefaultRequest
	(*timestamp.Timestamp)(nil),      // 15: google.protobuf.Timestamp
}
var file_proto_mafia_game_proto_depIdxs = []int32{
	0,  // 0: SessionReadiness.role:type_name -> Roles
	2,  // 1: ConnectToSessionResponse.readiness:type_name -> SessionReadiness
	1,  // 2: ListConnectionsResponse.state:type_name -> State
	15, // 3: ListConnectionsResponse.time:type_name -> google.protobuf.Timestamp
	2,  // 4: ListConnectionsResponse.readiness:type_name -> SessionReadiness
	0,  // 5: VoteForMafiaResponse.killed_user_role:type_name -> Roles
	0,  // 6: GameStatus.winner:type_name -> Roles
	10, // 7: StatusResponse.game_status:type_name -> GameStatus
	14, // 8: MafiaService.ConnectToSession:input_type -> DefaultRequest
	14, // 9: MafiaService.LeaveSession:input_type -> DefaultRequest
	14, // 10: MafiaService.ListConnections:input_type -> DefaultRequest
	6,  // 11: MafiaService.VoteForMafia:input_type -> VoteForMafiaRequest
	8,  // 12: MafiaService.MakeMove:input_type -> MoveRequest
	14, // 13: MafiaService.StartDay:input_type -> DefaultRequest
	14, // 14: MafiaService.GetStatus:input_type -> DefaultRequest
	14, // 15: MafiaService.ExitGameSession:input_type -> DefaultRequest
	3,  // 16: MafiaService.ConnectToSession:output_type -> ConnectToSessionResponse
	4,  // 17: MafiaService.LeaveSession:output_type -> LeaveSessionResponse
	5,  // 18: MafiaService.ListConnections:output_type -> ListConnectionsResponse
	7,  // 19: MafiaService.VoteForMafia:output_type -> VoteForMafiaResponse
	9,  // 20: MafiaService.MakeMove:output_type -> MoveResponse
	11, // 21: MafiaService.StartDay:output_type -> DayResponse
	12, // 22: MafiaService.GetStatus:output_type -> StatusResponse
	13, // 23: MafiaService.ExitGameSession:output_type -> ExitGameSessionResponse
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_mafia_game_proto_init() }
func file_proto_mafia_game_proto_init() {
	if File_proto_mafia_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_mafia_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionReadiness); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mafia_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectToSessionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mafia_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveSessionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mafia_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListConnectionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mafia_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteForMafiaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mafia_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteForMafiaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mafia_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mafia_game_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mafia_game_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mafia_game_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mafia_game_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mafia_game_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExitGameSessionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mafia_game_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_mafia_game_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mafia_game_proto_goTypes,
		DependencyIndexes: file_proto_mafia_game_proto_depIdxs,
		EnumInfos:         file_proto_mafia_game_proto_enumTypes,
		MessageInfos:      file_proto_mafia_game_proto_msgTypes,
	}.Build()
	File_proto_mafia_game_proto = out.File
	file_proto_mafia_game_proto_rawDesc = nil
	file_proto_mafia_game_proto_goTypes = nil
	file_proto_mafia_game_proto_depIdxs = nil
}
